<?php
add_filter( 'osf_customize_colors', 'osf_typography_custom_color', 10, 7 );
function osf_typography_custom_color($cssCode, $color_primary, $color_primary_hover, $color_secondary, $color_secondary_hover, $color_body, $color_heading) {
    $cssCode .= <<<CSS

input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="number"],
input[type="tel"],
input[type="range"],
input[type="date"],
input[type="month"],
input[type="week"],
input[type="time"],
input[type="datetime"],
input[type="datetime-local"],
input[type="color"],
textarea,
.mainmenu-container ul ul .menu-item > a,
.mainmenu-container li a span,
.breadcrumb a,
.breadcrumb span,
.widget .tagcloud a,
.widget.widget_tag_cloud a,
.c-body,
.site-header-account .account-links-menu li a,
.site-header-account .account-dashboard li a,
.comment-reply-link,
.comment-form label,
.comment-form a,
.widget a,
.opal-custom-menu-inline .widget_nav_menu li ul a,
.cart-collaterals .cart_totals th,
#payment .payment_methods li.woocommerce-notice,
#payment .payment_methods li.woocommerce-notice--info,
#payment .payment_methods li.woocommerce-info,
table.woocommerce-checkout-review-order-table th,
.opal-style-1.search-form-wapper .search-submit span,
.opal-style-1.search-form-wapper .search-submit span:before,
.product-style-1 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-1 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.product-style-2 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-2 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.product-style-3 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-3 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.product-style-4 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-4 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.product-style-5 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-5 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.owl-theme.woocommerce-carousel.nav-style-4 .owl-nav .owl-prev,
.owl-theme.woocommerce-carousel.nav-style-4 .owl-nav .owl-next,
.owl-theme.owl-carousel.nav-style-4 .owl-nav .owl-prev,
.woocommerce .woocommerce-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-prev,
.woocommerce-product-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-prev,
.owl-theme.owl-carousel.nav-style-4 .owl-nav .owl-next,
.woocommerce .woocommerce-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-next,
.woocommerce-product-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-next,
.owl-theme .products.nav-style-4 .owl-nav .owl-prev,
.owl-theme .products.nav-style-4 .owl-nav .owl-next,
.mc4wp-form .widget-title p .c-body,
.mc4wp-form .widget-title p .site-header-account .account-links-menu li a,
.site-header-account .account-links-menu li .mc4wp-form .widget-title p a,
.mc4wp-form .widget-title p .site-header-account .account-dashboard li a,
.site-header-account .account-dashboard li .mc4wp-form .widget-title p a,
.mc4wp-form .widget-title p .comment-reply-link,
.mc4wp-form .widget-title p .comment-form label,
.comment-form .mc4wp-form .widget-title p label,
.mc4wp-form .widget-title p .comment-form a,
.comment-form .mc4wp-form .widget-title p a,
.mc4wp-form .widget-title p .widget a,
.widget .mc4wp-form .widget-title p a,
.mc4wp-form .widget-title p .opal-custom-menu-inline .widget_nav_menu li ul a,
.opal-custom-menu-inline .widget_nav_menu li ul .mc4wp-form .widget-title p a,
.mc4wp-form .widget-title p .cart-collaterals .cart_totals th,
.cart-collaterals .cart_totals .mc4wp-form .widget-title p th,
.mc4wp-form .widget-title p #payment .payment_methods li.woocommerce-notice,
#payment .payment_methods .mc4wp-form .widget-title p li.woocommerce-notice,
.mc4wp-form .widget-title p #payment .payment_methods li.woocommerce-notice--info,
#payment .payment_methods .mc4wp-form .widget-title p li.woocommerce-notice--info,
.mc4wp-form .widget-title p #payment .payment_methods li.woocommerce-info,
#payment .payment_methods .mc4wp-form .widget-title p li.woocommerce-info,
.mc4wp-form .widget-title p table.woocommerce-checkout-review-order-table th,
table.woocommerce-checkout-review-order-table .mc4wp-form .widget-title p th,
.mc4wp-form .widget-title p .opal-style-1.search-form-wapper .search-submit span,
.opal-style-1.search-form-wapper .search-submit .mc4wp-form .widget-title p span,
.mc4wp-form .widget-title p .opal-style-1.search-form-wapper .search-submit span:before,
.opal-style-1.search-form-wapper .search-submit .mc4wp-form .widget-title p span:before,
.mc4wp-form .widget-title p .product-style-1 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.product-style-1 li.product:not(.elementor-style) .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.mc4wp-form .widget-title p .elementor-product-style-1 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-1 li.elementor-style .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.mc4wp-form .widget-title p .product-style-2 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.product-style-2 li.product:not(.elementor-style) .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.mc4wp-form .widget-title p .elementor-product-style-2 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-2 li.elementor-style .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.mc4wp-form .widget-title p .product-style-3 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.product-style-3 li.product:not(.elementor-style) .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.mc4wp-form .widget-title p .elementor-product-style-3 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-3 li.elementor-style .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.mc4wp-form .widget-title p .product-style-4 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.product-style-4 li.product:not(.elementor-style) .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.mc4wp-form .widget-title p .elementor-product-style-4 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-4 li.elementor-style .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.mc4wp-form .widget-title p .product-style-5 li.product:not(.elementor-style) .yith-wcwl-add-to-wishlist > div > a:before,
.product-style-5 li.product:not(.elementor-style) .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.mc4wp-form .widget-title p .elementor-product-style-5 li.elementor-style .yith-wcwl-add-to-wishlist > div > a:before,
.elementor-product-style-5 li.elementor-style .mc4wp-form .widget-title p .yith-wcwl-add-to-wishlist > div > a:before,
.woocommerce-shipping-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.woocommerce-billing-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.opal-currency_switcher .list-currency button[type="submit"],
.select-items div,
.single-product div.product .product_meta .sku_wrapper span,
.single-product div.product .product_meta .sku_wrapper a,
.single-product div.product .product_meta .posted_in span,
.single-product div.product .product_meta .posted_in a,
.single-product div.product .product_meta .tagged_as span,
.single-product div.product .product_meta .tagged_as a,
.widget .woof_list_label li .woof_label_term {
  color: {$color_body}; }



.entry-content blockquote cite a,
.entry-content strong,
.entry-content dt,
.entry-content th,
.entry-content dt a,
.entry-content th a,
.column-item.post-style-1 .entry-category a,
.comment-content table th,
.comment-content table td a,
.comment-content dt,
h2.widget-title,
h2.widgettitle,
.c-heading,
.form-group .form-row label,
fieldset legend,
.vertical-navigation .menu-open-label,
article.type-post .entry-meta a,
.related-heading,
.author-wrapper .author-name,
.post-navigation .nav-title,
.blog article.type-post .more-link,
.blog article.type-page .more-link,
.archive article.type-post .more-link,
.archive article.type-page .more-link,
.search article.type-post .more-link,
.search article.type-page .more-link,
.search .entry-header a,
.column-item .entry-title a,
.column-item .link-more a,
.column-item .entry-tags a,
.page .entry-header .entry-title,
.site-header-account .login-form-title,
.comments-title,
table.shop_table_responsive tbody th,
.site-header-cart .widget_shopping_cart p.total .woocommerce-Price-amount,
.site-header-cart .shopping_cart_nav p.total .woocommerce-Price-amount,
.filter-toggle,
.filter-close,
table.cart:not(.wishlist_table) th,
table.cart:not(.wishlist_table) .product-name a,
table.cart:not(.wishlist_table) .product-subtotal .woocommerce-Price-amount,
.cart-collaterals .cart_totals .order-total .woocommerce-Price-amount,
.cart-collaterals .cart_totals .amount,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info,
#payment .payment_methods > .wc_payment_method > label,
table.woocommerce-checkout-review-order-table .order-total .woocommerce-Price-amount,
table.woocommerce-checkout-review-order-table .product-name,
.woocommerce-billing-fields label,
.woocommerce-billing-fields > h3,
.cart th,
.shop_table th,
.woocommerce-account .woocommerce-MyAccount-content strong,
.woocommerce-account .woocommerce-MyAccount-content .woocommerce-Price-amount,
.osf-sorting .display-mode button.active,
.osf-sorting .display-mode button:hover,
.woocommerce-Tabs-panel table.shop_attributes th,
#osf-accordion-container table.shop_attributes th,
.woocommerce-tabs#osf-accordion-container [data-accordion] [data-control],
.widget .woof_list_checkbox input[type="checkbox"] + label:after,
.widget .woof_list_checkbox input[type="checkbox"]:checked + label,
.widget .woof_list_radio input[type="radio"]:checked + label {
  color: {$color_heading}; }



.btn-link,
.button-link,
.more-link,
blockquote:before,
.mainmenu-container li.current-menu-parent > a,
.mainmenu-container .menu-item > a:hover,
.cat-tags-links .tags-links a:hover,
.pbr-social-share a:hover,
.column-item.post-style-1 .entry-category a:hover,
.column-item.post-style-2 .post-inner .entry-title a:hover,
.column-item.post-style-2 .post-inner .entry-category a:hover,
.column-item.post-style-2 .post-inner .post-date a:hover,
.breadcrumb a:hover,
.button-outline-primary,
.widget_shopping_cart .buttons .button:nth-child(odd),
.c-primary,
.main-navigation .menu-item > a:hover,
.navigation-button .menu-toggle:hover,
.navigation-button .menu-toggle:focus,
.entry-title a:hover,
.entry-content blockquote cite a:hover,
article.type-post .entry-meta a:hover,
.opal-post-navigation-2 .post-navigation .nav-links .nav-previous a:hover:before,
.opal-post-navigation-2 .post-navigation .nav-links .nav-next a:hover:before,
.search .entry-header a:hover,
.error404 .go-back:hover,
.error404 .page-content .search-form button.search-submit:hover,
.scrollup:hover .icon,
.site-header-account .account-dropdown a.register-link,
.site-header-account .account-dropdown a.lostpass-link,
.site-header-account .account-links-menu li a:hover,
.site-header-account .account-dashboard li a:hover,
.comment-form a:hover,
.widget a:hover,
.widget a:focus,
.widget h2.widget-title a:hover,
.widget h2.widget-title a:focus,
.widget h2.widgettitle a:hover,
.widget h2.widgettitle a:focus,
.widget .tagcloud a:hover,
.widget .tagcloud a:focus,
.widget.widget_tag_cloud a:hover,
.widget.widget_tag_cloud a:focus,
.wp_widget_tag_cloud a:hover,
.wp_widget_tag_cloud a:focus,
.opal-custom-menu-inline .widget ul li a:hover,
.owl-theme.woocommerce-carousel.nav-style-4 .owl-nav .owl-prev:hover,
.owl-theme.woocommerce-carousel.nav-style-4 .owl-nav .owl-next:hover,
.owl-theme.owl-carousel.nav-style-4 .owl-nav .owl-prev:hover,
.woocommerce .woocommerce-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-prev:hover,
.woocommerce-product-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-prev:hover,
.owl-theme.owl-carousel.nav-style-4 .owl-nav .owl-next:hover,
.woocommerce .woocommerce-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-next:hover,
.woocommerce-product-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-next:hover,
.owl-theme .products.nav-style-4 .owl-nav .owl-prev:hover,
.owl-theme .products.nav-style-4 .owl-nav .owl-next:hover,
#secondary .elementor-widget-container h5:first-of-type,
.elementor-nav-menu-popup .mfp-close,
.site-header-cart .widget_shopping_cart .product_list_widget li a:hover,
.site-header-cart .widget_shopping_cart .product_list_widget li a:focus,
.site-header-cart .shopping_cart_nav .product_list_widget li a:hover,
.site-header-cart .shopping_cart_nav .product_list_widget li a:focus,
.site-header-cart .woocommerce-mini-cart__empty-message:before,
.header-button:hover,
.header-button:focus,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a:hover,
.woocommerce-privacy-policy-link,
.opal-currency_switcher .list-currency button[type="submit"]:hover,
.opal-currency_switcher .list-currency li.active button[type="submit"],
ul.products li.product.osf-product-list .price,
ul.products li.product .posfed_in a:hover,
.select-items div:hover,
.button-wrapper #chart-button,
.product_list_widget a:hover,
.product_list_widget a:active,
.product_list_widget a:focus,
.woocommerce-product-list a:hover,
.woocommerce-product-list a:active,
.woocommerce-product-list a:focus,
.product-style-1 li.product:not(.elementor-style) h2 a:hover,
.product-style-1 li.product:not(.elementor-style) h3 a:hover,
.product-style-1 li.product:not(.elementor-style) .woocommerce-loop-product__title a:hover,
.elementor-product-style-1 li.elementor-style h2 a:hover,
.elementor-product-style-1 li.elementor-style h3 a:hover,
.elementor-product-style-1 li.elementor-style .woocommerce-loop-product__title a:hover,
.product-style-2 li.product:not(.elementor-style) h2 a:hover,
.product-style-2 li.product:not(.elementor-style) h3 a:hover,
.product-style-2 li.product:not(.elementor-style) .woocommerce-loop-product__title a:hover,
.elementor-product-style-2 li.elementor-style h2 a:hover,
.elementor-product-style-2 li.elementor-style h3 a:hover,
.elementor-product-style-2 li.elementor-style .woocommerce-loop-product__title a:hover,
.product-style-3 li.product:not(.elementor-style) h2 a:hover,
.product-style-3 li.product:not(.elementor-style) h3 a:hover,
.product-style-3 li.product:not(.elementor-style) .woocommerce-loop-product__title a:hover,
.elementor-product-style-3 li.elementor-style h2 a:hover,
.elementor-product-style-3 li.elementor-style h3 a:hover,
.elementor-product-style-3 li.elementor-style .woocommerce-loop-product__title a:hover,
.product-style-4 li.product:not(.elementor-style) h2 a:hover,
.product-style-4 li.product:not(.elementor-style) h3 a:hover,
.product-style-4 li.product:not(.elementor-style) .woocommerce-loop-product__title a:hover,
.elementor-product-style-4 li.elementor-style h2 a:hover,
.elementor-product-style-4 li.elementor-style h3 a:hover,
.elementor-product-style-4 li.elementor-style .woocommerce-loop-product__title a:hover,
.product-style-5 li.product:not(.elementor-style) h2 a:hover,
.product-style-5 li.product:not(.elementor-style) h3 a:hover,
.product-style-5 li.product:not(.elementor-style) .woocommerce-loop-product__title a:hover,
.elementor-product-style-5 li.elementor-style h2 a:hover,
.elementor-product-style-5 li.elementor-style h3 a:hover,
.elementor-product-style-5 li.elementor-style .woocommerce-loop-product__title a:hover,
.owl-theme.woocommerce-carousel.nav-style-2 .owl-nav [class*=owl]:hover:before,
.owl-theme.owl-carousel.nav-style-2 .owl-nav [class*=owl]:hover:before,
.woocommerce .woocommerce-carousel ul.owl-theme.nav-style-2.products .owl-nav [class*=owl]:hover:before,
.woocommerce-product-carousel ul.owl-theme.nav-style-2.products .owl-nav [class*=owl]:hover:before,
.owl-theme .products.nav-style-2 .owl-nav [class*=owl]:hover:before,
.owl-theme.woocommerce-carousel.nav-style-3 .owl-nav [class*=owl]:hover:before,
.owl-theme.owl-carousel.nav-style-3 .owl-nav [class*=owl]:hover:before,
.woocommerce .woocommerce-carousel ul.owl-theme.nav-style-3.products .owl-nav [class*=owl]:hover:before,
.woocommerce-product-carousel ul.owl-theme.nav-style-3.products .owl-nav [class*=owl]:hover:before,
.owl-theme .products.nav-style-3 .owl-nav [class*=owl]:hover:before,
#secondary .elementor-widget-wp-widget-recent-posts a,
.elementor-widget-opal-box-overview .elementor-box-overview-wrapper .entry-header a,
.elementor-widget-icon-box:hover .elementor-icon,
.woocommerce-MyAccount-navigation ul li.is-active a,
.widget_product_categories ul li a:hover,
.widget_rating_filter ul li a:hover,
.woocommerce-widget-layered-nav ul li a:hover,
.widget_product_brands ul li a:hover,
.widget_product_categories ul li.current-cat a,
.widget_rating_filter ul li.current-cat a,
.woocommerce-widget-layered-nav ul li.current-cat a,
.widget_product_brands ul li.current-cat a {
  color: {$color_primary->toCss()}; }


input[type="button"]:hover,
input[type="button"]:focus,
input[type="submit"]:hover,
input[type="submit"]:focus,
button[type="submit"]:hover,
button[type="submit"]:focus,
.page-links .page-number,
.column-item .entry-tags a:hover,
.opal-comment-form-2 .comment-form input[type="submit"]:hover,
.opal-comment-form-3 .comment-form input[type="submit"]:hover,
.opal-comment-form-2 .comment-form input[type="submit"]:active,
.opal-comment-form-3 .comment-form input[type="submit"]:active,
.opal-comment-form-2 .comment-form input[type="submit"]:focus,
.opal-comment-form-3 .comment-form input[type="submit"]:focus,
.widget .tagcloud a:hover:before,
.widget .tagcloud a:focus:before,
.widget.widget_tag_cloud a:hover:before,
.widget.widget_tag_cloud a:focus:before,
.wp_widget_tag_cloud a:hover:before,
.wp_widget_tag_cloud a:focus:before,
section.widget_price_filter .ui-slider .ui-slider-range,
.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.button-outline-primary:hover,
.widget_shopping_cart .buttons .button:hover:nth-child(odd),
.button-outline-primary:active,
.widget_shopping_cart .buttons .button:active:nth-child(odd),
.button-outline-primary.active,
.widget_shopping_cart .buttons .active.button:nth-child(odd),
.show > .button-outline-primary.dropdown-toggle,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button:nth-child(odd),
.bg-primary,
[class*="after-title"]:after,
.before-title-primary:before,
.owl-theme.woocommerce-carousel .owl-dots .owl-dot:hover,
.owl-theme.woocommerce-carousel .owl-dots .owl-dot.active,
.owl-theme.owl-carousel .owl-dots .owl-dot:hover,
.woocommerce .woocommerce-carousel ul.owl-theme.products .owl-dots .owl-dot:hover,
.woocommerce-product-carousel ul.owl-theme.products .owl-dots .owl-dot:hover,
.owl-theme.owl-carousel .owl-dots .owl-dot.active,
.woocommerce .woocommerce-carousel ul.owl-theme.products .owl-dots .owl-dot.active,
.woocommerce-product-carousel ul.owl-theme.products .owl-dots .owl-dot.active,
.owl-theme .products .owl-dots .owl-dot:hover,
.owl-theme .products .owl-dots .owl-dot.active,
.elementor-widget-divider .elementor-divider-separator:before,
.header-button .count,
.notification-added-to-cart .ns-content,
#payment .place-order .button:hover,
form.track_order p:last-of-type button[type="submit"]:hover,
form.track_order p:last-of-type button[type="submit"]:focus,
form.register .button[type="submit"]:hover,
#yith-quick-view-modal ::-webkit-scrollbar-thumb,
#yith-quick-view-modal :window-inactive::-webkit-scrollbar-thumb,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:hover,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:active,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:focus,
.woocommerce-tabs ul.tabs li a:after,
.single-product .single_add_to_cart_button:hover,
.single-product .single_add_to_cart_button.disabled[type="submit"]:hover,
.widget_price_filter .ui-slider .ui-slider-handle,
.widget_price_filter .ui-slider .ui-slider-range,
.handheld-footer-bar .cart .footer-cart-contents .count {
  background-color: {$color_primary->toCss()}; }


.form-control:focus,
input[type="text"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="password"]:focus,
input[type="search"]:focus,
input[type="number"]:focus,
input[type="tel"]:focus,
input[type="range"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="week"]:focus,
input[type="time"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="color"]:focus,
textarea:focus,
input[type="button"]:hover,
input[type="button"]:focus,
input[type="submit"]:hover,
input[type="submit"]:focus,
button[type="submit"]:hover,
button[type="submit"]:focus,
.cat-tags-links .tags-links a:hover,
.column-item .entry-tags a:hover,
.error404 .go-back,
.error404 .page-content .search-form button.search-submit,
.opal-comment-form-2 .comment-form input[type="submit"]:hover,
.opal-comment-form-3 .comment-form input[type="submit"]:hover,
.opal-comment-form-2 .comment-form input[type="submit"]:active,
.opal-comment-form-3 .comment-form input[type="submit"]:active,
.opal-comment-form-2 .comment-form input[type="submit"]:focus,
.opal-comment-form-3 .comment-form input[type="submit"]:focus,
.widget .tagcloud a:hover:after,
.widget .tagcloud a:focus:after,
.widget.widget_tag_cloud a:hover:after,
.widget.widget_tag_cloud a:focus:after,
.wp_widget_tag_cloud a:hover:after,
.wp_widget_tag_cloud a:focus:after,
.widget .tagcloud a:hover,
.widget .tagcloud a:focus,
.widget.widget_tag_cloud a:hover,
.widget.widget_tag_cloud a:focus,
.wp_widget_tag_cloud a:hover,
.wp_widget_tag_cloud a:focus,
.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.button-outline-primary,
.widget_shopping_cart .buttons .button:nth-child(odd),
.button-outline-primary:hover,
.widget_shopping_cart .buttons .button:hover:nth-child(odd),
.button-outline-primary:active,
.widget_shopping_cart .buttons .button:active:nth-child(odd),
.button-outline-primary.active,
.widget_shopping_cart .buttons .active.button:nth-child(odd),
.show > .button-outline-primary.dropdown-toggle,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button:nth-child(odd),
.b-primary,
.owl-theme.woocommerce-carousel.nav-style-2 .owl-nav [class*=owl]:hover,
.owl-theme.owl-carousel.nav-style-2 .owl-nav [class*=owl]:hover,
.woocommerce .woocommerce-carousel ul.owl-theme.nav-style-2.products .owl-nav [class*=owl]:hover,
.woocommerce-product-carousel ul.owl-theme.nav-style-2.products .owl-nav [class*=owl]:hover,
.owl-theme .products.nav-style-2 .owl-nav [class*=owl]:hover,
.owl-theme.woocommerce-carousel.nav-style-4 .owl-nav .owl-prev:hover,
.owl-theme.woocommerce-carousel.nav-style-4 .owl-nav .owl-next:hover,
.owl-theme.owl-carousel.nav-style-4 .owl-nav .owl-prev:hover,
.woocommerce .woocommerce-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-prev:hover,
.woocommerce-product-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-prev:hover,
.owl-theme.owl-carousel.nav-style-4 .owl-nav .owl-next:hover,
.woocommerce .woocommerce-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-next:hover,
.woocommerce-product-carousel ul.owl-theme.nav-style-4.products .owl-nav .owl-next:hover,
.owl-theme .products.nav-style-4 .owl-nav .owl-prev:hover,
.owl-theme .products.nav-style-4 .owl-nav .owl-next:hover,
#payment .place-order .button:hover,
form.track_order p:last-of-type button[type="submit"]:hover,
form.track_order p:last-of-type button[type="submit"]:focus,
form.track_order p input[type="text"]:hover,
form.track_order p input[type="text"]:focus,
form.register .button[type="submit"]:hover,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:hover,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:active,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:focus,
.single-product .single_add_to_cart_button:hover,
.single-product .single_add_to_cart_button.disabled[type="submit"]:hover,
.single-product.woocommerce-single-style-4 .flex-nav-next a:hover:after,
.single-product.woocommerce-single-style-4 .flex-nav-prev a:hover:after,
.widget_product_categories ul li a:hover:before,
.widget_rating_filter ul li a:hover:before,
.woocommerce-widget-layered-nav ul li a:hover:before,
.widget_product_brands ul li a:hover:before,
.widget_product_categories ul li.current-cat a:before,
.widget_rating_filter ul li.current-cat a:before,
.woocommerce-widget-layered-nav ul li.current-cat a:before,
.widget_product_brands ul li.current-cat a:before,
.woocommerce-widget-layered-nav ul li.chosen a.osf-color-type:after,
.osf-product-deal .woocommerce-product-list .opal-countdown .day,
.otf-product-recently-content li:hover .product-thumbnail img {
  border-color: {$color_primary->toCss()}; }



.btn-link:focus,
.btn-link:hover,
.button-link:focus,
.more-link:focus,
.button-link:hover,
.more-link:hover,
a:hover,
a:active {
  color: {$color_primary_hover->toCss()}; }


.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button {
  background-color: {$color_primary_hover->toCss()}; }


.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button {
  border-color: {$color_primary_hover->toCss()}; }



.button-outline-secondary,
.c-secondary,
.author-wrapper .author-name h6,
.list-feature-box > li:before,
.elementor-widget-opal-box-overview .elementor-box-overview-wrapper .entry-header a:hover {
  color: {$color_secondary->toCss()}; }


.button-secondary,
.secondary-button .search-submit,
.button-outline-secondary:hover,
.button-outline-secondary:active,
.button-outline-secondary.active,
.show > .button-outline-secondary.dropdown-toggle,
.bg-secondary,
.before-title-secondary:before,
#secondary .elementor-widget-wp-widget-categories a:before,
#secondary .elementor-nav-menu a:before,
.e--pointer-dot a:before {
  background-color: {$color_secondary->toCss()}; }


.button-secondary,
.secondary-button .search-submit,
.button-outline-secondary,
.button-outline-secondary:hover,
.button-outline-secondary:active,
.button-outline-secondary.active,
.show > .button-outline-secondary.dropdown-toggle,
.b-secondary {
  border-color: {$color_secondary->toCss()}; }



.button-secondary:hover,
.secondary-button .search-submit:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit {
  background-color: {$color_secondary_hover->toCss()}; }


.button-secondary:hover,
.secondary-button .search-submit:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit {
  border-color: {$color_secondary_hover->toCss()}; }


CSS;
    return $cssCode;
}
add_filter('osf_customize_grid', 'osf_typography_grid_bootstrap', 10 , 2);
function osf_typography_grid_bootstrap($cssCode, $gridGutter){
    $cssCode .= <<<CSS

.row,
body.opal-content-layout-2cl #content .wrap,
body.opal-content-layout-2cr #content .wrap,
[data-opal-columns],
.opal-archive-style-4.blog .site-main,
.opal-archive-style-4.archive .site-main,
.opal-default-content-layout-2cr .site-content .wrap,
.site-footer .widget-area,
.opal-comment-form-2 .comment-form,
.opal-comment-form-3 .comment-form,
.opal-comment-form-4 .comment-form,
.opal-comment-form-6 .comment-form,
.widget .gallery,
.elementor-element .gallery,
.entry-gallery .gallery,
.single .gallery,
.list-feature-box,
[data-elementor-columns],
.opal-canvas-filter.top .opal-canvas-filter-wrap,
.opal-canvas-filter.top .opal-canvas-filter-wrap section.WOOF_Widget .woof_redraw_zone,
.woocommerce-cart .woocommerce,
.woocommerce-billing-fields .woocommerce-billing-fields__field-wrapper,
.woocommerce-MyAccount-content form[class^="woocommerce-"],
.woocommerce-columns--addresses,
.woocommerce-account .woocommerce,
.woocommerce-Addresses,
.woocommerce-address-fields__field-wrapper,
ul.products,
.osf-sorting,
.single-product div.product,
.single-product div.product .woocommerce-product-gallery .flex-control-thumbs {
    margin-right: -{$gridGutter}px;
    margin-left: -{$gridGutter}px;
}



.col-1,
.col-2,
[data-elementor-columns-mobile="6"] .column-item,
.col-3,
[data-elementor-columns-mobile="4"] .column-item,
.col-4,
.opal-comment-form-2 .comment-form .comment-form-author,
.opal-comment-form-3 .comment-form .comment-form-author,
.opal-comment-form-2 .comment-form .comment-form-email,
.opal-comment-form-3 .comment-form .comment-form-email,
.opal-comment-form-2 .comment-form .comment-form-url,
.opal-comment-form-3 .comment-form .comment-form-url,
[data-elementor-columns-mobile="3"] .column-item,
.col-5,
.col-6,
.opal-comment-form-4 .comment-form .comment-form-author,
.opal-comment-form-4 .comment-form .comment-form-email,
.opal-comment-form-4 .comment-form .comment-form-url,
.opal-comment-form-6 .comment-form .comment-form-author,
.opal-comment-form-6 .comment-form .comment-form-email,
[data-elementor-columns-mobile="2"] .column-item,
.single-product.opal-comment-form-2 .comment-form-author,
.single-product.opal-comment-form-3 .comment-form-author,
.single-product.opal-comment-form-2 .comment-form-email,
.single-product.opal-comment-form-3 .comment-form-email,
.col-7,
.col-8,
.col-9,
.col-10,
.col-11,
.col-12,
.related-posts .column-item,
.site-footer .widget-area .widget-column,
.opal-comment-form-2 .comment-form .logged-in-as,
.opal-comment-form-3 .comment-form .logged-in-as,
.opal-comment-form-2 .comment-form .comment-notes,
.opal-comment-form-3 .comment-form .comment-notes,
.opal-comment-form-2 .comment-form .comment-form-comment,
.opal-comment-form-3 .comment-form .comment-form-comment,
.opal-comment-form-2 .comment-form .form-submit,
.opal-comment-form-3 .comment-form .form-submit,
.opal-comment-form-4 .comment-form .logged-in-as,
.opal-comment-form-4 .comment-form .comment-notes,
.opal-comment-form-4 .comment-form .comment-form-comment,
.opal-comment-form-4 .comment-form .form-submit,
.opal-comment-form-6 .comment-form .logged-in-as,
.opal-comment-form-6 .comment-form .comment-notes,
.opal-comment-form-6 .comment-form .comment-form-comment,
.opal-comment-form-6 .comment-form .comment-form-url,
.opal-comment-form-6 .comment-form .form-submit,
.widget .gallery-columns-1 .gallery-item,
.elementor-element .gallery-columns-1 .gallery-item,
.entry-gallery .gallery-columns-1 .gallery-item,
.single .gallery-columns-1 .gallery-item,
[data-elementor-columns-mobile="1"] .column-item,
.elementor-single-product .single-product div.product .entry-summary,
.woocommerce-cart .cart-empty,
.woocommerce-cart .return-to-shop,
.woocommerce-billing-fields .form-row-wide,
.woocommerce-MyAccount-content form[class^="woocommerce-"] > *:not(fieldset),
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-wide,
#customer_details [class*='col'],
.woocommerce-Addresses .woocommerce-Address,
.columns-1 ul.products li.product,
.columns-1 ul.products > li,
#reviews .comment-form-rating,
.col,
body #secondary,
.mfp-content .comment-form-rating,
.opal-canvas-filter.top .opal-canvas-filter-wrap section,
.opal-canvas-filter.top .opal-canvas-filter-wrap section.WOOF_Widget .woof_redraw_zone .woof_container,
.columns-5 ul.products li.product,
.columns-5 ul.products > li,
.col-auto,
.col-sm-1,
[data-opal-columns="12"] .column-item,
.col-sm-2,
[data-opal-columns="6"] .column-item,
.columns-6 ul.products li.product,
.columns-6 ul.products > li,
.col-sm-3,
[data-opal-columns="4"] .column-item,
.col-sm-4,
[data-opal-columns="3"] .column-item,
.widget .gallery-columns-6 .gallery-item,
.elementor-element .gallery-columns-6 .gallery-item,
.entry-gallery .gallery-columns-6 .gallery-item,
.single .gallery-columns-6 .gallery-item,
.col-sm-5,
.col-sm-6,
[data-opal-columns="2"] .column-item,
.widget .gallery-columns-2 .gallery-item,
.elementor-element .gallery-columns-2 .gallery-item,
.entry-gallery .gallery-columns-2 .gallery-item,
.single .gallery-columns-2 .gallery-item,
.widget .gallery-columns-3 .gallery-item,
.elementor-element .gallery-columns-3 .gallery-item,
.entry-gallery .gallery-columns-3 .gallery-item,
.single .gallery-columns-3 .gallery-item,
.widget .gallery-columns-4 .gallery-item,
.elementor-element .gallery-columns-4 .gallery-item,
.entry-gallery .gallery-columns-4 .gallery-item,
.single .gallery-columns-4 .gallery-item,
.list-feature-box > li,
.woocommerce-billing-fields .form-row-first,
.woocommerce-billing-fields .form-row-last,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-first,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-last,
ul.products li.product,
.columns-2 ul.products li.product,
.columns-2 ul.products > li,
.columns-3 ul.products li.product,
.columns-3 ul.products > li,
.columns-4 ul.products li.product,
.columns-4 ul.products > li,
.opal-content-layout-2cl .columns-3 ul.products li.product,
.opal-content-layout-2cl .columns-3 ul.products > li,
.opal-content-layout-2cr .columns-3 ul.products li.product,
.opal-content-layout-2cr .columns-3 ul.products > li,
.col-sm-7,
.col-sm-8,
.col-sm-9,
.col-sm-10,
.col-sm-11,
.col-sm-12,
[data-opal-columns="1"] .column-item,
.cart-collaterals .cross-sells,
.woocommerce-columns--addresses .woocommerce-column,
.woocommerce-account .woocommerce-MyAccount-navigation,
.woocommerce-account .woocommerce-MyAccount-content,
.woocommerce-address-fields__field-wrapper .form-row,
.woocommerce-product-carousel ul.products li.product,
.osf-sorting .woocommerce-message,
.osf-sorting .woocommerce-notice,
.opal-content-layout-2cl .osf-sorting .osf-sorting-group,
.opal-content-layout-2cr .osf-sorting .osf-sorting-group,
.single-product div.product .images,
.single-product div.product .entry-summary,
.single-product.woocommerce-single-style-3 div.product .entry-summary,
.single-product.woocommerce-single-style-4 div.product .entry-summary,
.single-product.woocommerce-single-style-3 div.product .images,
.single-product.woocommerce-single-style-4 div.product .images,
.col-sm,
.col-sm-auto,
.col-md-1,
.col-md-2,
[data-elementor-columns-tablet="6"] .column-item,
.col-md-3,
[data-elementor-columns-tablet="4"] .column-item,
.col-md-4,
[data-elementor-columns-tablet="3"] .column-item,
.col-md-5,
.opal-default-content-layout-2cr #secondary,
.osf-sorting .osf-sorting-group,
.col-md-6,
[data-elementor-columns-tablet="2"] .column-item,
.col-md-7,
.opal-default-content-layout-2cr #primary,
.osf-sorting .osf-sorting-group + .osf-sorting-group,
.col-md-8,
.col-md-9,
.col-md-10,
.col-md-11,
.col-md-12,
[data-elementor-columns-tablet="1"] .column-item,
.cart-collaterals,
.col-md,
.col-md-auto,
.col-lg-1,
.col-lg-2,
[data-elementor-columns="6"] .column-item,
.col-lg-3,
[data-elementor-columns="4"] .column-item,
.col-lg-4,
[data-elementor-columns="3"] .column-item,
.col-lg-5,
.col-lg-6,
.opal-default-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cl .related-posts .column-item,
[data-elementor-columns="2"] .column-item,
.col-lg-7,
.col-lg-8,
.opal-content-layout-2cl .osf-sorting .osf-sorting-group + .osf-sorting-group,
.opal-content-layout-2cr .osf-sorting .osf-sorting-group + .osf-sorting-group,
.col-lg-9,
.col-lg-10,
.col-lg-11,
.col-lg-12,
[data-elementor-columns="1"] .column-item,
.col-lg,
.col-lg-auto,
.col-xl-1,
.col-xl-2,
.col-xl-3,
.col-xl-4,
.col-xl-5,
.col-xl-6,
.col-xl-7,
.col-xl-8,
.col-xl-9,
.col-xl-10,
.col-xl-11,
.col-xl-12,
.col-xl,
.col-xl-auto {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}



.container,
#content,
.opal-canvas-filter.top,
.single-product .related.products,
.single-product .up-sells.products,
.otf-product-recently-content .widget_recently_viewed_products {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}
  @media (min-width: 576px) {
    .container, #content, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 540px; } }
  @media (min-width: 768px) {
    .container, #content, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 720px; } }
  @media (min-width: 992px) {
    .container, #content, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 960px; } }
  @media (min-width: 1200px) {
    .container, #content, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 1440px; } }


CSS;
    return $cssCode;
}
add_filter('osf_customize_button_primary_color', 'osf_typography_button_primary_color', 10 , 11);
function osf_typography_button_primary_color($cssCode, $primary, $primary_hover, $primary_border, $primary_border_hover, $primary_color, $primary_color_hover, $border_radius, $primary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS

.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button {
    background-color: {$primary};
    border-color: {$primary};
    color: {$primary_color};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button {
    background-color: {$primary_hover};
    border-color: {$primary_hover};
    color: {$primary_color_hover};
    {$button_css}
}


CSS;
    return $cssCode;
}

add_filter('osf_customize_button_secondary_color', 'osf_typography_button_secondary_color', 10 , 11);
function osf_typography_button_secondary_color($cssCode, $secondary, $secondary_hover, $secondary_border, $secondary_border_hover, $secondary_color, $secondary_color_hover, $border_radius, $secondary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS

.button-secondary,
.secondary-button .search-submit {
    background-color: {$secondary};
    border-color: {$secondary};
    color: {$secondary_color};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-secondary:hover,
.secondary-button .search-submit:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit {
    background-color: {$secondary_hover};
    border-color: {$secondary_hover};
    color: {$secondary_color};
    {$button_css}
    {$font_style_code}
}


CSS;
    return $cssCode;
}
add_filter('osf_customize_typo_heading', 'osf_typography_custom_typo_heading', 10 , 2);
function osf_typography_custom_typo_heading($cssCode, $heading_css){
    $cssCode .= <<<CSS

.typo-heading,
.author-wrapper .author-name,
.post-navigation .nav-subtitle,
.post-navigation .nav-title,
h2.widget-title,
h2.widgettitle,
#secondary .elementor-widget-container h5:first-of-type,
.osf-product-deal .woocommerce-product-list .opal-countdown {
    {$heading_css}
}


CSS;
    return $cssCode;
}
